import Head from 'next/head'

import { Button } from 'react-bootstrap'

// https://techy-api.vercel.app/api/json
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
